add some snippets for Volto blocks
plone/plone-vs-snippets pull request #16
Opened 2024-12-29 17:54 UTC by erral

In this PR I add snippets for:

- Volto block config
- Volto block schema
- Volto block View component
- Volto block Edit component
- Volto schema enhancer function

2024-12-29 21:08 UTC, stevepiercy requested changes
Docs should go into the `README.md` for better visibility.

2024-12-29 21:08 UTC, stevepiercy commented on CHANGELOG.md
> +- Add snippets to create volto blocks
```suggestion
- Add snippets to create Volto blocks.
```

2024-12-29 21:08 UTC, stevepiercy commented on snippets/javascript.json
> +  // }
JSON does not support comments. I think this documentation as well as the one for JSReact would be best moved into `README.md`, after the existing XML and Python screenshots, with both this commented documentation and a screenshot of it in action in the VSCode editor.

2025-01-22 06:42 UTC, davisagli approved these changes

2025-01-22 06:42 UTC, davisagli commented on snippets/javascript.json
> +      "const schemaEnhancerVariation = ({ formData, schema, intl}) => {",
I wouldn't use "variation" here; that's something else.

2025-01-22 07:27 UTC, erral commented on snippets/javascript.json
> +      "const schemaEnhancerVariation = ({ formData, schema, intl}) => {",
you mean in the function name, right?

2025-01-22 15:58 UTC, erral commented on snippets/javascript.json
> +      "const schemaEnhancerVariation = ({ formData, schema, intl}) => {",
I have renamed it to `voltoSchemaEnhancer`

2025-01-22 16:03 UTC, davisagli approved these changes

2025-01-23 10:36 UTC, sneridagh approved these changes

2025-05-09 12:06 UTC, merged

2025-05-26 15:57 UTC, MrTango commented
release 1.0.7 is done ;)